name: subida-dockerhub
on: [push]
jobs:
  construccion-subida-del-contenedor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker build -t jantoniovr/iv-2021-2022 .
      - run: docker push jantoniovr/iv-2021-2022
      
  sincronizacion_readme_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dockerhub Readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          readme: "./README.md"
          repository: jantoniovr/iv-2021-2022
      
